### ISSUE TITLE
Doesn't work on websites using ssl or tls.

### ISSUE THREAD

**Issue by DarkLinkXXXX** [rocktronica/Add-CSS-Bookmarklet#1]

**Comment by rocktronica** [comment]
True, unfortunately. It's a limitation with GH pages, and that's the price I'm paying for using them as my CDN.

Closing the issue, but thanks for flagging it!

**Comment by krystian3w** [comment]
Now fixed.

**Comment by krystian3w** [comment]
https://github.com/rocktronica/Add-CSS-Bookmarklet/pull/2
